#!/bin/sh
#This script is for schheduling start & stop time for list of EC2 instances
#
#This code generates three Lambda functions:
# 	start-func : Its responsible to START the list of EC2 instances mentioned in the list.
# 	stop-func : Its responsible to STOP the list of EC2 instances mentioned in the list.
# 	reset-func : Its responsible to reset the events back to default on Sunday night at 11:59PM.
#
#There are 17 events generated by this code:
# 	two of them are default for START and STOP each.
# 	14 of them are for each day of the week, in which 7 are for START and remaining 7 for STOP.
# 	and the last event is for resetting all scheduled events BACK TO DEFAULT.
REGION='us-east-1'
echo 'Enter default start time'
read myStartTime
echo 'Enter default stop time'
read myStopTime

#Setting up default rules.................
echo 'Creating Start Rule.....'
default_start_rule_arn=$(aws events put-rule \
--name start-rule \
--region $REGION \
--schedule-expression "cron(0 ${myStartTime} ? * MON-FRI *)" \
--query 'RuleArn' \
--output text)
echo 'Creating stop rule.....'
default_stop_rule_arn=$(aws events put-rule \
--name stop-rule \
--region $REGION \
--schedule-expression "cron(0 ${myStopTime} ? * MON-FRI *)" \
--query 'RuleArn' \
--output text)
echo "Creating reset rule....."
default_reset_rule_arn=$(aws events put-rule \
--name reset-rule \
--region $REGION \
--schedule-expression "cron(59 23 ? * SUN *)" \
--query 'RuleArn' \
--output text)

#Lambda functions starts here...................
#lambda start-func
echo -e "import boto3\nregion = '${REGION}'\ninstances = ['']\ndef lambda_handler(event, context):\n    print(event)\n    ec2 = boto3.client('ec2', region_name=region)\n    ec2.start_instances(InstanceIds=instances)\n    print 'Welcome starting your instances.....'" > start-func.py
zip tempzip.zip start-func.py
temp=$(aws lambda create-function --function-name start-func \
--runtime python3.6 \
--role arn:aws:iam::488599217855:role/FullAccess \
--handler start-func.lambda_handler \
--zip-file fileb://tempzip.zip \
--timeout 300 \
--region $REGION)
#fetching arn
startFunctionArn=$(aws lambda get-function-configuration --function-name start-func --region $REGION --query "FunctionArn" --output text)
echo "Your start function is created!"
rm start-func.py tempzip.zip
#setting up target
echo 'Creating start Targets.....'
echo "[
  {
    \"Id\": "\"1\"", 
    \"Arn\": "\""$startFunctionArn"\""
  }
]" > target-start.json
aws events put-targets \
--rule start-rule \
--targets file://target-start.json \
--region $REGION

#lambda stop-func
echo "time for stop function"
echo -e "import boto3\nregion = '${REGION}'\ninstances = ['i-0c88bb86fedfcc299']\ndef lambda_handler(event, context):\n    print(event)\n    ec2 = boto3.client('ec2', region_name=region)\n    ec2.stop_instances(InstanceIds=instances)\n    return 'GoodBye see you soon.....'" > stop-func.py
zip tempzip.zip stop-func.py
temp=$(aws lambda create-function --function-name stop-func \
--runtime python3.6 \
--role arn:aws:iam::488599217855:role/FullAccess \
--handler stop-func.lambda_handler \
--zip-file fileb://tempzip.zip \
--timeout 300 \
--region $REGION)
#fetching arn
stopFunctionArn=$(aws lambda get-function-configuration --function-name stop-func --region $REGION --query "FunctionArn" --output text)
echo "Your stop function is created!"
rm stop-func.py tempzip.zip
#generating target for rule
echo 'Creating stop Targets.....'
echo "[
  {
    \"Id\": "\"1\"", 
    \"Arn\": "\""$stopFunctionArn"\""
  }
]" > target-stop.json
aws events put-targets \
--rule stop-rule \
--targets file://target-stop.json \
--region $REGION

#lambda reset-func
echo -e "import boto3\na = ['MON', 'TUE', 'WED', 'THUR', 'FRI', 'SAT', 'SUN']\ndef lambda_handler(event, context):\n    client = boto3.client('events')\n    for i in range(0,7):\n        response = client.disable_rule(Name=a[i]+'-start-rule')\n        response = client.disable_rule(Name=a[i]+'-stop-rule')\n    response = client.enable_rule(Name='start-rule' )\n    response = client.enable_rule(Name='stop-rule')\n    return 'Hello from Lambda'" > reset-func.py
zip tempzip.zip reset-func.py
temp=$(aws lambda create-function --function-name reset-func \
--runtime python3.6 \
--role arn:aws:iam::488599217855:role/FullAccess \
--handler reset-func.lambda_handler \
--zip-file fileb://tempzip.zip \
--timeout 300 \
--region $REGION)
#fetching ARN
resetFunctionArn=$(aws lambda get-function-configuration \
--function-name reset-func \
--region $REGION \
--query "FunctionArn" \
--output text)
echo "Your reset function is created!"
rm reset-func.py tempzip.zip
#JSON target for reset-rule
echo 'Creating reset targets.....'
echo "[
  {
    \"Id\": "\"1\"", 
    \"Arn\": "\""$resetFunctionArn"\""
  }
]" > target-reset.json
aws events put-targets \
--rule reset-rule \
--targets file://target-reset.json \
--region $REGION
rm target-reset.json

#Time for adding Lambda trigger permissions to default rules
echo 'adding permissions to lambda...'
#start rule
aws lambda add-permission \
--function-name start-func \
--statement-id start-event \
--region $REGION \
--action 'lambda:InvokeFunction' \
--principal events.amazonaws.com \
--source-arn $default_start_rule_arn
#stop rule
aws lambda add-permission \
--function-name stop-func \
--statement-id stop-event \
--region $REGION \
--action 'lambda:InvokeFunction' \
--principal events.amazonaws.com \
--source-arn $default_stop_rule_arn
#reset rule
aws lambda add-permission \
--function-name reset-func \
--statement-id reset-event \
--region $REGION \
--action 'lambda:InvokeFunction' \
--principal events.amazonaws.com \
--source-arn $default_reset_rule_arn

#Generating rules for each day of the week
# i.e start and stop rules for a day
days=( [0]="MON" [1]="TUE" [2]="WED" [3]="THUR" [4]="FRI" [5]="SAT" [6]="SUN")
starttime=0
endtime=1
echo "going inside for loop....DND"
for ((i=0;i<7;i++))
do
#setting up start rule for each days.....
	tempArn=$(aws events put-rule \
		--name ${days[i]}-start-rule \
		--region $REGION \
		--schedule-expression "cron(0 ${starttime} ? * ${days[i]} *)" \
		--query 'RuleArn' \
		--output text)
	aws events put-targets \
	--rule ${days[i]}-start-rule \
	--targets file://target-start.json \
	--region $REGION
	aws lambda add-permission \
	--function-name start-func \
	--statement-id ${days[i]}-start-event \
	--region $REGION \
	--action 'lambda:InvokeFunction' \
	--principal events.amazonaws.com \
	--source-arn $tempArn
	aws events disable-rule \
	--name ${days[i]}-start-rule \
	--region $REGION
#setting up stop rule for each days.....
	tempArn=$(aws events put-rule \
	--name ${days[i]}-stop-rule \
	--region $REGION \
	--schedule-expression "cron(0 ${endtime} ? * ${days[i]} *)" \
	--query 'RuleArn' \
	--output text)
	aws events put-targets \
	--rule ${days[i]}-stop-rule \
	--targets file://target-stop.json \
	--region $REGION
	aws lambda add-permission \
	--function-name stop-func \
	--statement-id ${days[i]}-stop-event \
	--region $REGION \
   --action 'lambda:InvokeFunction' \
	--principal events.amazonaws.com \
	--source-arn $tempArn
	aws events disable-rule \
	--name ${days[i]}-stop-rule \
	--region $REGION
done
rm target-start.json target-stop.json
echo "Setup Done.....!"